# Generated by Django 6.1.1 on 2026-09-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='aadhar_number',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='room',
        ),
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.TextField(default='Not Available'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(default='Not Available', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='emergency_contact',
            field=models.CharField(default='Not Available', max_length=15),
            preserve_default=False,
        ),
    ]
