# Generated by Django 6.1.1 on 2026-09-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('PG', 'PG'), ('HOSTEL', 'Hostel'), ('APARTMENT', 'Apartment')], max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_phone', models.CharField(max_length=15)),
            ],
        ),
    ]
