# Generated by Django 6.1.1 on 2026-09-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='entry_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
