# Generated by Django 6.1.1 on 2026-09-26 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beds', '0001_initial'),
        ('tenants', '0002_rename_name_tenant_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_date', models.DateField()),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('bed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='beds.bed')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
    ]
